# Generated by Django 4.1.7 on 2023-02-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clanovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30, verbose_name='Ime')),
                ('prezime', models.CharField(max_length=30, verbose_name='Prezime')),
                ('telefon', models.CharField(max_length=30, verbose_name='Kontakt Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adresa')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=120, verbose_name='Naziv Mesta')),
                ('adresa', models.CharField(max_length=300, verbose_name='Adresa Mesta')),
                ('pos_broj', models.CharField(max_length=15, verbose_name='poštanski Broj')),
                ('telefon', models.CharField(max_length=30, verbose_name='Kontakt Telefon')),
                ('web', models.URLField(verbose_name='Web Adresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adresa')),
            ],
        ),
        migrations.CreateModel(
            name='Evant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=120, verbose_name='Ime Dogadjaja')),
                ('event_datum', models.DateTimeField(verbose_name='Dan Dogadjaja')),
                ('menadzer', models.CharField(max_length=60)),
                ('opis', models.TextField(blank=True)),
                ('polaznici', models.ManyToManyField(blank=True, to='events.clanovi')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
        ),
    ]
