# Generated by Django 4.1.7 on 2023-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Adresa'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Kontakt Telefon'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.URLField(blank=True, verbose_name='Web Adresa'),
        ),
    ]
