# Generated by Django 4.1.7 on 2023-02-19 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_venue_email_alter_venue_telefon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evant',
            name='menadzer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
