# Generated by Django 4.1.7 on 2023-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_evant_menadzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='vlasnik',
            field=models.IntegerField(default=1, verbose_name='Vlasnik događaja'),
        ),
    ]
